### ISSUE TITLE
Error when running task on EXTERNAL instance

### ISSUE THREAD

**Issue by min9pm8** [aws-containers/ecs-anywhere-tutorial#2]
https://github.com/aws-containers/ecs-anywhere-tutorial/blame/master/README.md#L172

Massimo,

I received the error below when testing an external instance in the shell script listed in the line above. I tested it with a Rasberry-Pi and then again with a local VM debian instance. Both registered fine with the cluster but when executing the task `ecsworker-external-task-def.json`, it gave the following error in CW logs and the task went from PENDING to STOPPED. Am I doing something wrong here? Thanks.

Paavan

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by min9pm8** [comment]
I was trying to run the amd64 image on my M1 Mac Mini ARM vm.

**Comment by mreferre** [comment]
:)
